### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by aciccarello** [aciccarello/aciccarello.github.io#21]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by aciccarello** [comment]
Material design web [lists dark mode](https://material.io/design/color/dark-theme.html#implementation) as planned. There currently is some support with SASS. The only open issue I could find was about [documenting dark mode with SASS](https://github.com/material-components/material-components-web/issues/1761)

Using raw CSS, I came up with the following, but SASS is probably better.
```css
@media (prefers-color-scheme: dark) {
	html {
		color: var(--mdc-theme-text-primary-on-dark, white);
		background: black;
	}
	main {
		background-color: #121212;
	}
	a,
	a.mdc-list-item,
	.mdc-list-item__secondary-text,
	a.mdc-card__primary {
		color: white;
	}
	.mdc-card {
		background-color: #1f1b24;
	}
}
```
